resources:
 repositories:
  - repository: vcpkg
    type: github
    endpoint: GithubAuth
    name: celestiamobile/vcpkg

stages:
- stage: Windows
  displayName: 'Windows'
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: windows

- stage: UWP
  displayName: 'UWP'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      buildTarget: uwp
