resources:
 repositories:
  - repository: vcpkg
    type: github
    endpoint: GithubAuth
    name: levinli303/vcpkg

pool:
  vmImage: windows-2022

steps:
- checkout: vcpkg
  path: vcpkg
  fetchDepth: 0

- script: |
    git checkout origin/celestia
  displayName: 'Checkout Branch'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/018c4587-05c3-4ee5-885e-27362b084c67'
    view: 
    definition: 'b1cdeeaf-bdb3-4129-b24e-c50396d00423'
    version: '1.0.0'
    downloadPath: '$(Agent.BuildDirectory)/vcpkg'

- script: |
    dir
    ls
  displayName: 'Bootstrap'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- script: |
    .\bootstrap-vcpkg.bat
  displayName: 'Bootstrap'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- script: |
    .\vcpkg --triplet=x64-uwp install --recurse libzip[core]
  displayName: 'Build'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- script: |
    .\vcpkg export --triplet=x64-uwp --nuget --nuget-version=$(VERSION) --nuget-id=celestia-uwp-dependencies libzip
  displayName: 'Export'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Agent.BuildDirectory)/vcpkg/celestia-uwp-dependencies.$(VERSION).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/018c4587-05c3-4ee5-885e-27362b084c67'