resources:
 repositories:
  - repository: vcpkg
    type: github
    endpoint: GithubAuth
    name: celestiamobile/vcpkg

stages:
- stage: x64
  displayName: 'x64'
  jobs:
  - template: jobs/build.yml
    parameters:
      arch: x64

- stage: arm64
  displayName: 'arm64'
  dependsOn: []
  jobs:
  - template: jobs/build.yml
    parameters:
      arch: arm64
