resources:
 repositories:
  - repository: vcpkg
    type: github
    endpoint: GithubAuth
    name: levinli303/vcpkg

trigger:
- main

pool:
  vmImage: windows-2022

steps:
- checkout: vcpkg
  path: vcpkg

- script: |
    dir
    ls
    git reset --hard origin/celestia
  displayName: 'Checkout Branch'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- task: NuGetToolInstaller@1
  displayName: 'Install Nuget'
