resources:
 repositories:
  - repository: vcpkg
    type: github
    endpoint: GithubAuth
    name: levinli303/vcpkg

trigger:
- main

pool:
  vmImage: windows-2022

steps:
- checkout: vcpkg
  path: vcpkg
  fetchDepth: 0

- script: |
    git checkout origin/celestia
  displayName: 'Checkout Branch'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- task: NuGetToolInstaller@1
  displayName: 'Install Nuget'

- script: |
    .\bootstrap-vcpkg.bat
  displayName: 'Bootstrap'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg

- script: |
    .\vcpkg install libpng:x64-uwp
  displayName: 'Build'
  workingDirectory: $(Agent.BuildDirectory)/vcpkg
