jobs:
- job: "Main"
  timeoutInMinutes: 120
  pool:
    vmImage: windows-2025

  variables:
    buildTarget: ${{ parameters.buildTarget }}

  steps:
  - checkout: vcpkg
    path: vcpkg
    fetchDepth: 0

  - script: |
      git checkout origin/celestia
    displayName: 'Checkout Branch'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg

  - script: |
      .\bootstrap-vcpkg.bat
    displayName: 'Bootstrap'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg

  - script: |
      set VCPKG_BINARY_SOURCES=clear
      .\vcpkg --triplet=x64-$(buildTarget) install --recurse libpng libjpeg-turbo gettext lua fmt eigen3 freetype[core] cspice libzip[core] meshoptimizer miniaudio boost-container boost-smart-ptr
    displayName: 'Build (UWP)'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg
    condition: eq( variables['buildTarget'], 'uwp' )

  - script: |
      set VCPKG_BINARY_SOURCES=clear
      .\vcpkg --triplet=x64-$(buildTarget) install --recurse libepoxy libpng libjpeg-turbo gettext luajit fmt eigen3 freetype[core] cspice libzip[core] meshoptimizer miniaudio boost-container boost-smart-ptr sentry-native
    displayName: 'Build (Windows)'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg
    condition: eq( variables['buildTarget'], 'windows-release' )

  - script: |
      .\vcpkg export --triplet=x64-$(buildTarget) --nuget --nuget-version=$(VERSION) --nuget-id=celestia-$(buildTarget)-dependencies libpng libjpeg-turbo gettext lua fmt eigen3 freetype cspice libzip  meshoptimizer miniaudio boost-container boost-smart-ptr
    displayName: 'Export (UWP)'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg
    condition: and(eq( variables['buildTarget'], 'uwp' ), ne( variables['VERSION'], '' ))

  - script: |
      .\vcpkg export --triplet=x64-$(buildTarget) --nuget --nuget-version=$(VERSION) --nuget-id=celestia-$(buildTarget)-dependencies libepoxy libpng libjpeg-turbo gettext luajit fmt eigen3 freetype cspice libzip  meshoptimizer miniaudio boost-container boost-smart-ptr sentry-native
    displayName: 'Export (Windows)'
    workingDirectory: $(Agent.BuildDirectory)/vcpkg
    condition: and(eq( variables['buildTarget'], 'windows-release' ), ne( variables['VERSION'], '' ))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Agent.BuildDirectory)/vcpkg/celestia-$(buildTarget)-dependencies.$(VERSION).nupkg'
      ArtifactName: '$(buildTarget)'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'
    condition: and(eq( variables['buildTarget'], 'windows-release' ), ne( variables['VERSION'], '' ))

  - task: NuGetCommand@2
    displayName: 'Publish Package'
    inputs:
      command: 'push'
      packagesToPush: '$(Agent.BuildDirectory)/vcpkg/celestia-$(buildTarget)-dependencies.$(VERSION).nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '9f9dcde1-dcba-4537-8214-71c8a03b99a0/14bb1031-e6b2-40ac-b287-73e7fcb5900e'
    condition: and(eq( variables['buildTarget'], 'windows-release' ), ne( variables['VERSION'], '' ))
